apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
kind: TalosControlPlane
metadata:
  name: aliktb-dev-talos-cp
spec:
  controlPlaneConfig:
    controlplane:
      generateType: controlplane
      talosVersion: v1.11
      strategicPatches:
      - |
        - op: replace
          path: /machine/install
          value:
            disk: /dev/sda
            image: factory.talos.dev/nocloud-installer/ce4c980550dd2ab1b17bbf2b08801c7eb59418eafe8f279833297925d67c7515:v1.11.1
        - op: add
          path: /machine/install/extraKernelArgs
          value:
          - net.ifnames=0
        - op: add
          path: /machine/network/interfaces
          value:
          - interface: eth0
            dhcp: false
            vip:
              ip: 192.168.0.102
        - op: add
          path: /machine/kubelet/extraArgs
          value:
            cloud-provider: external
  infrastructureTemplate:
    kind: ProxmoxMachineTemplate
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    name: aliktb-dev-cp
    namespace: default
  version: v1.34.0
