apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
kind: TalosConfigTemplate
metadata:
  name: aliktb-dev-talosconfig-workers
spec:
  template:
    spec:
      configPatches:
      - op: replace
        path: /machine/install
        value:
          disk: /dev/sda
      generateType: worker
      talosVersion: v1.11
